apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-and-media-shop.fullname" . }}-shop-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mail-and-media-shop.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.shopdb.auth.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-and-media-shop.fullname" . }}-keycloak-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mail-and-media-shop.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.keycloakdb.auth.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-and-media-shop.fullname" . }}-keycloak-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mail-and-media-shop.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.keycloak.auth.adminPassword | quote }}
  client-secret: {{ .Values.keycloak.auth.clientSecret | quote }}
