stages:
  - test
  - e2e-test
  - package
  - deploy
  - deploy-live

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  
before_script:
  - source scripts/utils.sh
  - source scripts/env_loader.sh

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository/
    - e2e_tests/venv/

unit_test_job:
  stage: test
  variables:
    REDIS_HOST: redis
  services:
    - name: redis:7.0-alpine
      alias: redis
  script:
    - mvn clean install
  tags:
    - maven

e2e_test_job:
  stage: e2e-test
  script:
    - chmod +x scripts/1_docker-e2e-setup.sh
    - chmod +x scripts/3_e2e-test-runner.sh
    - ./scripts/1_docker-e2e-setup.sh
    - ./scripts/3_e2e-test-runner.sh
  artifacts:
    when: always
    paths:
      - logs/
  tags:
    - maven

package_job:
  stage: package
  dependencies:
    - unit_test_job
    - e2e_test_job
  script:
    - chmod +x scripts/4_docker-package.sh
    - ./scripts/4_docker-package.sh
  tags:
    - maven

deploy_dev:
  stage: deploy
  dependencies:
    - package_job
  environment:
    name: dev
    url: https://${SSH_HOST}/dev
  script:
    - chmod +x scripts/5_deploy-dev.sh
    - ./scripts/5_deploy-dev.sh
  when: manual
  tags:
    - maven

deploy_qa:
  stage: deploy
  dependencies:
    - package_job
  environment:
    name: qa
    url: https://${SSH_HOST}/qa
  script:
    - chmod +x scripts/6_deploy-qa.sh
    - ./scripts/6_deploy-qa.sh
  when: manual
  tags:
    - maven

deploy_live:
  stage: deploy-live
  dependencies:
    - package_job
  environment:
    name: live
    url: https://${SSH_HOST}
  script:
    - chmod +x scripts/7_deploy-live.sh
    - ./scripts/7_deploy-live.sh
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  when: manual
  allow_failure: false
  tags:
    - maven
