services:

  shop_db:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SHOP_DB_USER} -d ${SHOP_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${SHOP_DB_NAME}
      POSTGRES_USER: ${SHOP_DB_USER}
      POSTGRES_PASSWORD: ${SHOP_DB_PASSWORD}
    ports:
      - "${SHOP_DB_PORT}:5432"
    volumes:
      - shop_db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mail_and_media_shop_v2:app
    depends_on:
      shop_db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8090"
    environment:
      - DB_URL=jdbc:postgresql://shop_db:5432/${SHOP_DB_NAME}
      - DB_USERNAME=${SHOP_DB_USER}
      - DB_PASSWORD=${SHOP_DB_PASSWORD}

volumes:
  shop_db_data:
