# Application identity
spring.application.name=mail-and-media-shop

# Embedded server
server.port=8080

# Billing domain configuration

billing.minimal-discount-amount=0.10
billing.zero-amount=0.00


# Logging
logging.level.dev.mam.buizsol.mamshop=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n