{{- if and .Values.shopdb.inline .Values.shopdb.legacyPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mail-and-media-shop.fullname" . }}-shop-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.shopdb.primary.persistence.size }}
{{- end }}
